export var mySampleAllReviews = {
    reviews: [
        {
            review: {
                id: 11,
                diner_name: "xvb cxv",
                creation_date: "2024-04-20T10:01:01.349090-04:00",
                number_of_stars: 5,
                review_comment: "Está demasiado rico este lomito encebollado",
                public_rejected: true,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Lomito Encebollado",
            },
            review_rejection: {
                rejection_reason: {
                    id: 2,
                    reason: "Contenido Irrelevante",
                },
            },
        },
        {
            review: {
                id: 10,
                diner_name: "el secuestrador",
                creation_date: "2024-04-19T18:49:25.177955-04:00",
                number_of_stars: 4,
                review_comment: "Demasiado rica la pizza con jamón",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza con Jamón",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 9,
                diner_name: "William",
                creation_date: "2024-04-19T18:49:25.171953-04:00",
                number_of_stars: 2,
                review_comment:
                    "La mejor pizza picante que me he comido hasta ahora",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza Picante",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 8,
                diner_name: "Petra",
                creation_date: "2024-04-19T18:49:25.170953-04:00",
                number_of_stars: 2,
                review_comment: "Pídanla esta pízza vegetariana. Es muy buena",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza Vegetariana",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 7,
                diner_name: "José",
                creation_date: "2024-04-19T18:49:25.169953-04:00",
                number_of_stars: 2,
                review_comment:
                    "Me voy a llevar otra pizza margarita, Me gustó mucho",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza Margarita",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 6,
                diner_name: "Carlos",
                creation_date: "2024-04-19T18:49:25.168952-04:00",
                number_of_stars: 5,
                review_comment:
                    "Me gustó mucho la pizza picante. La recomiendo",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza Picante",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 5,
                diner_name: "Pierre",
                creation_date: "2024-04-19T18:49:25.167952-04:00",
                number_of_stars: 2,
                review_comment: "Me gustó esta Pizza Picante",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza Picante",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 4,
                diner_name: "Gloria",
                creation_date: "2024-04-19T18:49:25.166952-04:00",
                number_of_stars: 3,
                review_comment:
                    "Me gustó esta Pizza Picante, es demasiado buena, me encantó, además de que una de las más sabrosas que he probado",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza Picante",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 3,
                diner_name: "juán",
                creation_date: "2024-04-19T18:49:25.165953-04:00",
                number_of_stars: 5,
                review_comment: "Este blacw&white es muy bueno",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Black & White",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 2,
                diner_name: "Esteban",
                creation_date: "2024-04-19T18:49:25.164953-04:00",
                number_of_stars: 5,
                review_comment: "Esta pizza margarita es muy buena",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "dish",
                parent_name: "Pizza Margarita",
            },
            review_rejection: {},
        },
        {
            review: {
                id: 1,
                diner_name: "Daniel",
                creation_date: "2024-04-19T18:49:25.137951-04:00",
                number_of_stars: 5,
                review_comment:
                    "Me gustó mucho este restaurant Pizzería Da Bruno",
                public_rejected: false,
                private_rejected: false,
                rejection_status_just_changed: false,
                parent_type: "restaurant",
                parent_name: "IL Romano Pizza",
            },
            review_rejection: {},
        },
    ],
};

// good
