export const mySampleMenu = {
    restaurant: {
        id: 1,
        public_country: {
            id: 2,
            name: "Chile",
            alpha2_code: "CL",
            flag_image_url:
                "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1700851282/Chile_Flag_hahf0s.jpg",
            full_product_price: "300000.00",
            minimum_product_price: "250000.00",
        },
        private_country: null,
        price_type: "full_price",
        public_name: "IL Romano Pizza",
        private_name: "",
        public_description:
            "En este restaurant servimos las mejores pizzas que puedas encontrar",
        private_description: "",
        public_address:
            "Fray Camilo Henríquez 686. Apto 1401. Santiago de Chile",
        private_address: "",
        public_phone: "+56975703826",
        private_phone: "",
        public_website_url: "https://www.ilromano.cl/",
        private_website_url: "",
        public_facade_image_id: 10,
        private_facade_image_id: -1,
        public_logo_image_id: 9,
        private_logo_image_id: -1,
        public_show_images: true,
        private_show_images: false,
        public_show_restaurant_reviews: true,
        private_show_restaurant_reviews: true,
        public_show_dishes_reviews: true,
        private_show_dishes_reviews: true,
        public_currency_symbol: "CLP$",
        private_currency_symbol: "CLP$",
        public_show_prices: true,
        private_show_prices: true,
        public_instagram_url: "https://www.instagram.com/pizzeria_ilromano/",
        private_instagram_url: "",
        public_facebook_url: "https://www.facebook.com/ilromanopizzas",
        private_facebook_url: "",
        public_twitter_url: "https://twitter.com/raffitta18",
        private_twitter_url: "",
        public_monday_open_hour_in_minutes: 570,
        public_tuesday_open_hour_in_minutes: 570,
        public_wednesday_open_hour_in_minutes: 570,
        public_thursday_open_hour_in_minutes: 570,
        public_friday_open_hour_in_minutes: 660,
        public_saturday_open_hour_in_minutes: 660,
        public_sunday_open_hour_in_minutes: 660,
        private_monday_open_hour_in_minutes: 570,
        private_tuesday_open_hour_in_minutes: 570,
        private_wednesday_open_hour_in_minutes: 570,
        private_thursday_open_hour_in_minutes: 570,
        private_friday_open_hour_in_minutes: 660,
        private_saturday_open_hour_in_minutes: 660,
        private_sunday_open_hour_in_minutes: 660,
        public_monday_close_hour_in_minutes: -120,
        public_tuesday_close_hour_in_minutes: -120,
        public_wednesday_close_hour_in_minutes: -120,
        public_thursday_close_hour_in_minutes: -120,
        public_friday_close_hour_in_minutes: 150,
        public_saturday_close_hour_in_minutes: 150,
        public_sunday_close_hour_in_minutes: -360,
        private_monday_close_hour_in_minutes: 0,
        private_tuesday_close_hour_in_minutes: 0,
        private_wednesday_close_hour_in_minutes: 0,
        private_thursday_close_hour_in_minutes: 0,
        private_friday_close_hour_in_minutes: 0,
        private_saturday_close_hour_in_minutes: 0,
        private_sunday_close_hour_in_minutes: 0,
        _current_date: "2024-06-28",
        main_user_id: 1,
        previous_restaurant_number_of_reviews: 0,
        previous_restaurant_reviews_average: 0,
        update_image_uses: true,
        todays_random_number: 54,
        currently_logged_in: -1,
        logged_in_time: "2024-06-28:14:29:41",
        logged_out_time: "2024-06-28:14:29:56",
        logged_in_user_random_number: -1,
        menu_edition_is_pending: false,
        reviews_updates_are_pending: false,
        menu_sorting_is_pending: false,
        restaurant_deliveries_edition_is_pending: false,
        promotions_edition_is_pending: false,
        preferences_edition_is_pending: false,
        users_edition_is_pending: false,
        dont_allow_further_actions_to_this_user: false,
        restaurant_creation_date: "2024-06-21",
        number_of_pending_free_months: 1,
        last_payment_date: "2024-06-21",
    },
    countries: [
        {
            country: {
                id: 1,
                name: "USA",
                alpha2_code: "US",
                flag_image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1718743711/usa_gdabim.jpg",
                full_product_price: "321.00",
                minimum_product_price: "267.00",
            },
        },
        {
            country: {
                id: 2,
                name: "Chile",
                alpha2_code: "CL",
                flag_image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1700851282/Chile_Flag_hahf0s.jpg",
                full_product_price: "300000.00",
                minimum_product_price: "250000.00",
            },
        },
        {
            country: {
                id: 3,
                name: "Argentina",
                alpha2_code: "AR",
                flag_image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1703877212/Argentina_mdii3e.jpg",
                full_product_price: "290000.00",
                minimum_product_price: "242000.00",
            },
        },
    ],
    restaurant_reviews: {
        number_of_reviews: 1,
        reviews_average: 5.0,
        reviews: [
            {
                review: {
                    id: 1,
                    diner_name: "Daniel",
                    creation_date: "2024-06-21T10:59:31.172739-04:00",
                    number_of_stars: 5,
                    review_comment:
                        "Me gustó mucho este restaurant Pizzería Da Bruno",
                    public_rejected: false,
                    private_rejected: false,
                    rejection_status_just_changed: false,
                    parent_type: "restaurant",
                    parent_name: "IL Romano Pizza",
                    has_been_modified: false,
                },
                review_rejection: {},
            },
        ],
    },
    restaurant_delivery_companies: [
        {
            restaurant_delivery_company: {
                id: 2,
                public_token: "xyz propio",
                private_token: "",
                recently_created: false,
                marked_for_deletion: false,
                has_been_modified: false,
                delivery_company_details: {
                    id: 4,
                    name: "Propio",
                    company_image_url:
                        "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1703854967/Propio_jxt8ea.jpg",
                    url_template: "",
                    country: 2,
                },
            },
        },
        {
            restaurant_delivery_company: {
                id: 1,
                public_token: "il-romano-pizza/XKySqjlbTmij6oTWSFWQ3w",
                private_token: "",
                recently_created: false,
                marked_for_deletion: false,
                has_been_modified: false,
                delivery_company_details: {
                    id: 1,
                    name: "Uber Eats",
                    company_image_url:
                        "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1703854967/Uber_eats_msaqsi.jpg",
                    url_template:
                        "https://www.ubereats.com/cl/store/<**TokeN**>?diningMode=DELIVERY",
                    country: 2,
                },
            },
        },
    ],
    promotions: [
        {
            promotion: {
                id: 1,
                public_name: "Viernes de Damas",
                private_name: "",
                public_attractor_text: "Cervezas Gratis",
                private_attractor_text: "",
                public_promotion_text:
                    '<p>👩&nbsp;<span style="color: orange;">Viernes Femenino</span>&nbsp;👩:</p><p>Sólo por estos días 😊tenemos el&nbsp;<strong>viernes femenino</strong>, a partir de las 18 horas de ese viernes, con&nbsp;la compra de&nbsp;uno de&nbsp;<em>nuestros&nbsp;</em><span style="background-color: black;">platos</span></p><p>Tendrás:</p><ol><li><span style="color: blue;">Dos&nbsp;Cervezas&nbsp;</span>gratis 🍻</li><li>Mucho amor ❤️❤️❤️</li></ol><p><br></p>',
                private_promotion_text: "",
                recently_created: false,
                has_been_modified: false,
                marked_for_deletion: false,
            },
        },
        {
            promotion: {
                id: 2,
                public_name: "Sábado de Caballeros",
                private_name: "",
                public_attractor_text: "Cervezas Gratis",
                private_attractor_text: "",
                public_promotion_text:
                    '<p>🧑&nbsp;<span style="color: orange;">Sábado Masculino</span>🧑:</p><p><br></p><p>Sólo por estos días tenemos el <span style="color: blue;">Sábado Masculino</span>, a partir de las 18 horas de ese sábado, con la compra uno de nuestros platos</p><p>Tendrás:</p><ul><li><u>2 Cervezas</u> gratis 🍻</li></ul><p><br></p>',
                private_promotion_text: "",
                recently_created: false,
                has_been_modified: false,
                marked_for_deletion: false,
            },
        },
    ],
    rejection_reasons: [
        {
            rejection_reason: {
                id: 1,
                reason: "Contenido Inapropiado",
                explanation:
                    "Las revisiones que contengan lenguaje ofensivo, discursos de odio o contenido explícito, tales como contenido sexualmente explícito, contenido de violencia, etc., deben ser rechazadas para mantener un ambiente respetuoso y acogedor para todos los usuarios",
            },
        },
        {
            rejection_reason: {
                id: 2,
                reason: "Contenido Irrelevante",
                explanation:
                    "Las revisiones que no estén relacionadas con el plato o la experiencia gastronómica, como el spam o anuncios no relacionados, deben ser rechazadas",
            },
        },
        {
            rejection_reason: {
                id: 3,
                reason: "Información Falsa",
                explanation:
                    "Las revisiones que contengan información falsa o engañosa sobre el plato o el restaurante deben ser rechazadas para mantener la integridad de la plataforma",
            },
        },
        {
            rejection_reason: {
                id: 4,
                reason: "Ataque Personal",
                explanation:
                    "Las revisiones que ataquen personalmente o acosen a otros usuarios, al personal del restaurante o a individuos asociados con el restaurante deben ser rechazadas para prevenir conflictos y mantener un ambiente positivo",
            },
        },
        {
            rejection_reason: {
                id: 5,
                reason: "Contenido Promocional",
                explanation:
                    "Las revisiones que sean excesivamente promocionales o sesgadas, como las publicadas por el personal del restaurante o afiliados sin revelación, deben ser rechazadas para garantizar la imparcialidad y autenticidad",
            },
        },
        {
            rejection_reason: {
                id: 6,
                reason: "Incoherente o Incomprensible",
                explanation:
                    "Las revisiones que sean difíciles de entender o carezcan de coherencia podrían ser rechazadas",
            },
        },
        {
            rejection_reason: {
                id: 7,
                reason: "Violación de la Privacidad",
                explanation:
                    "Las revisiones que divulguen información personal sobre individuos sin su consentimiento, como el personal del restaurante u otros clientes, deben ser rechazadas para proteger la privacidad",
            },
        },
        {
            rejection_reason: {
                id: 8,
                reason: "Spam o Generado por Bots",
                explanation:
                    "Las revisiones generadas por bots o sistemas automatizados con el propósito de hacer spam o manipular calificaciones deben ser rechazadas para mantener la calidad del contenido generado por los usuarios",
            },
        },
        {
            rejection_reason: {
                id: 9,
                reason: "Reseña Deshonesta",
                explanation:
                    "Las revisiones que parezcan deshonestas o fabricadas con el propósito de promocionar o desprestigiar al restaurante deben ser rechazadas para garantizar la autenticidad de las reseñas de los usuarios",
            },
        },
        {
            rejection_reason: {
                id: 10,
                reason: "Solicitud del Usuario",
                explanation: "Por solicitud del mismo usuario",
            },
        },
    ],
    restaurant_users: [
        {
            restaurant_user: {
                id: 5,
                public_name: "Elsy",
                private_name: "",
                // public_phone: "67557575",
                // private_phone: "",
                public_image_id: -1,
                private_image_id: -1,
                public_password: "Chile.17",
                private_password: "",
                public_email: "rafael.soteldo@gmail.com",
                private_email: "",
                logged_in: false,
                last_logged_in: "2024-06-26:10:46:28",
                last_logged_out: "2024-06-26:10:47:04",
                recently_created: false,
                marked_for_deletion: false,
                main_user: false,
                has_been_modified: false,
                validated: false,
            },
        },
        {
            restaurant_user: {
                id: 1,
                public_name: "Rafael",
                private_name: "",
                // public_phone: "+56975703826",
                // private_phone: "",
                public_image_id: -1,
                private_image_id: -1,
                public_password: "Chile.17",
                private_password: "",
                public_email: "rafael.soteldo@gmail.com",
                private_email: "",
                logged_in: false,
                last_logged_in: "2024-06-28:14:29:41",
                last_logged_out: "2024-06-28:14:29:56",
                recently_created: false,
                marked_for_deletion: false,
                main_user: true,
                has_been_modified: false,
                validated: true,
            },
        },
    ],
    images: [
        {
            image: {
                id: 10,
                image_name: "Fachada",
                image_original_name: "il-romano-facade",
                image_public_id: "1/il-romano-facade_fklqrg",
                image_resource_type: "image",
                image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1719443212/1/il-romano-facade_fklqrg.jpg",
                use_count: 1,
                finished_setting: false,
                image_creation_date: "2024-06-26",
                image_next_revision_date: "2024-09-26",
            },
        },
        {
            image: {
                id: 9,
                image_name: "Logo",
                image_original_name: "il-romano-logo",
                image_public_id: "1/il-romano-logo_y2rsfz",
                image_resource_type: "image",
                image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1719443187/1/il-romano-logo_y2rsfz.jpg",
                use_count: 1,
                finished_setting: false,
                image_creation_date: "2024-06-26",
                image_next_revision_date: "2024-09-26",
            },
        },
        {
            image: {
                id: 2,
                image_name: "Pizza Picante",
                image_original_name: "Pizza-Picante",
                image_public_id: "1/Pizza-Picante_e5zioc",
                image_resource_type: "image",
                image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1718982199/1/Pizza-Picante_e5zioc.jpg",
                use_count: 1,
                finished_setting: false,
                image_creation_date: "2024-06-21",
                image_next_revision_date: "2024-09-21",
            },
        },
        {
            image: {
                id: 11,
                image_name: "Pizza Vegetariana",
                image_original_name: "pizza-vegetariana-t",
                image_public_id: "1/pizza-vegetariana-t_j1zuce",
                image_resource_type: "image",
                image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1719523207/1/pizza-vegetariana-t_j1zuce.jpg",
                use_count: 1,
                finished_setting: false,
                image_creation_date: "2024-06-27",
                image_next_revision_date: "2024-09-27",
            },
        },
        {
            image: {
                id: 1,
                image_name: "Pizzas",
                image_original_name: "pizzas",
                image_public_id: "1/pizzas_pnfr60",
                image_resource_type: "image",
                image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1718982159/1/pizzas_pnfr60.jpg",
                use_count: 1,
                finished_setting: false,
                image_creation_date: "2024-06-21",
                image_next_revision_date: "2024-09-21",
            },
        },
        {
            image: {
                id: 12,
                image_name: "yo",
                image_original_name: "captured_image",
                image_public_id: "1/captured_image_ih8y1f",
                image_resource_type: "image",
                image_url:
                    "https://res.cloudinary.com/dtrd4b7uc/image/upload/v1719540549/1/captured_image_ih8y1f.png",
                use_count: 0,
                finished_setting: false,
                image_creation_date: "2024-06-27",
                image_next_revision_date: "2024-09-28",
            },
        },
    ],
    categories: [
        {
            category: {
                id: 3,
                public_name: "Carnes",
                private_name: "",
                public_description: "Estas son las ricas carnes",
                private_description: "",
                public_view_order: 1,
                private_view_order: null,
                public_image_id: -1,
                private_image_id: -1,
                recently_created: false,
                has_been_modified: false,
                marked_for_deletion: false,
            },
            dishes: [
                {
                    dish: {
                        id: 4,
                        public_name: "Lomito Encebollado",
                        private_name: "",
                        public_description:
                            "Este es el delicioso Lomito Encebollado",
                        private_description: "",
                        public_price: "19000",
                        private_price: "0.0",
                        public_view_order: null,
                        private_view_order: null,
                        public_image_id: -1,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 0,
                    dish_number_of_reviews: 0,
                    reviews: [],
                },
            ],
        },
        {
            category: {
                id: 1,
                public_name: "Pizzas",
                private_name: "",
                public_description: "Estas son las ricas Pizzas",
                private_description: "",
                public_view_order: 2,
                private_view_order: null,
                public_image_id: 1,
                private_image_id: -1,
                recently_created: false,
                has_been_modified: false,
                marked_for_deletion: false,
            },
            dishes: [
                {
                    dish: {
                        id: 1,
                        public_name: "Pizza Picante",
                        private_name: "",
                        public_description:
                            "Esta es la deliciosa Pizza Picante",
                        private_description: "",
                        public_price: "8500",
                        private_price: "0.0",
                        public_view_order: 1,
                        private_view_order: null,
                        public_image_id: 2,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 3.4,
                    dish_number_of_reviews: 5,
                    reviews: [
                        {
                            review: {
                                id: 10,
                                diner_name: "dfgfds",
                                creation_date:
                                    "2024-06-21T11:01:31.269931-04:00",
                                number_of_stars: 5,
                                review_comment: "sdvsdavsdavgfdgvdfsvb",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Picante",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                        {
                            review: {
                                id: 8,
                                diner_name: "William",
                                creation_date:
                                    "2024-06-21T10:59:31.207739-04:00",
                                number_of_stars: 2,
                                review_comment:
                                    "La mejor pizza picante que me he comido hasta ahora",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Picante",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                        {
                            review: {
                                id: 5,
                                diner_name: "Carlos",
                                creation_date:
                                    "2024-06-21T10:59:31.203740-04:00",
                                number_of_stars: 5,
                                review_comment:
                                    "Me gustó mucho la pizza picante. La recomiendo",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Picante",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                        {
                            review: {
                                id: 4,
                                diner_name: "Pierre",
                                creation_date:
                                    "2024-06-21T10:59:31.202743-04:00",
                                number_of_stars: 2,
                                review_comment: "Me gustó esta Pizza Picante",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Picante",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                        {
                            review: {
                                id: 3,
                                diner_name: "Gloria",
                                creation_date:
                                    "2024-06-21T10:59:31.201738-04:00",
                                number_of_stars: 3,
                                review_comment:
                                    "Me gustó esta Pizza Picante, es demasiado buena, me encantó, además de que una de las más sabrosas que he probado",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Picante",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                    ],
                },
                {
                    dish: {
                        id: 2,
                        public_name: "Pizza Vegetariana",
                        private_name: "",
                        public_description:
                            "Esta es la deliciosa Pizza Vegetariana",
                        private_description: "",
                        public_price: "5500",
                        private_price: "0.0",
                        public_view_order: 2,
                        private_view_order: null,
                        public_image_id: 11,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 2.0,
                    dish_number_of_reviews: 1,
                    reviews: [
                        {
                            review: {
                                id: 7,
                                diner_name: "Petra",
                                creation_date:
                                    "2024-06-21T10:59:31.206739-04:00",
                                number_of_stars: 2,
                                review_comment:
                                    "Pídanla esta pízza vegetariana. Es muy buena",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Vegetariana",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                    ],
                },
                {
                    dish: {
                        id: 3,
                        public_name: "Pizza Margarita",
                        private_name: "",
                        public_description:
                            "Esta es la deliciosa Pizza Margarita",
                        private_description: "",
                        public_price: "4500",
                        private_price: "0.0",
                        public_view_order: null,
                        private_view_order: null,
                        public_image_id: -1,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 3.5,
                    dish_number_of_reviews: 2,
                    reviews: [
                        {
                            review: {
                                id: 6,
                                diner_name: "José",
                                creation_date:
                                    "2024-06-21T10:59:31.204738-04:00",
                                number_of_stars: 2,
                                review_comment:
                                    "Me voy a llevar otra pizza margarita, Me gustó mucho",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Margarita",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                        {
                            review: {
                                id: 2,
                                diner_name: "Esteban",
                                creation_date:
                                    "2024-06-21T10:59:31.200739-04:00",
                                number_of_stars: 5,
                                review_comment:
                                    "Esta pizza margarita es muy buena",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza Margarita",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                    ],
                },
                {
                    dish: {
                        id: 5,
                        public_name: "Pizza con Chorizo",
                        private_name: "",
                        public_description:
                            "Esta es la deliciosa Pizza con Chorizo",
                        private_description: "",
                        public_price: "7500",
                        private_price: "0.0",
                        public_view_order: null,
                        private_view_order: null,
                        public_image_id: -1,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 0,
                    dish_number_of_reviews: 0,
                    reviews: [],
                },
                {
                    dish: {
                        id: 6,
                        public_name: "Pizza con Jamón",
                        private_name: "",
                        public_description:
                            "Esta es la deliciosa Pizza con jamón",
                        private_description: "",
                        public_price: "8000",
                        private_price: "0.0",
                        public_view_order: null,
                        private_view_order: null,
                        public_image_id: -1,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 4.0,
                    dish_number_of_reviews: 1,
                    reviews: [
                        {
                            review: {
                                id: 9,
                                diner_name: "el secuestrador",
                                creation_date:
                                    "2024-06-21T10:59:31.210737-04:00",
                                number_of_stars: 4,
                                review_comment:
                                    "Demasiado rica la pizza con jamón",
                                public_rejected: false,
                                private_rejected: false,
                                rejection_status_just_changed: false,
                                parent_type: "dish",
                                parent_name: "Pizza con Jamón",
                                has_been_modified: false,
                            },
                            review_rejection: {},
                        },
                    ],
                },
            ],
        },
        {
            category: {
                id: 4,
                public_name: "Bebidas",
                private_name: "",
                public_description: "Estas son las ricas Bebidas",
                private_description: "",
                public_view_order: 3,
                private_view_order: null,
                public_image_id: -1,
                private_image_id: -1,
                recently_created: false,
                has_been_modified: false,
                marked_for_deletion: false,
            },
            dishes: [
                {
                    dish: {
                        id: 7,
                        public_name: "Limonada",
                        private_name: "",
                        public_description: "Esta es la fabulosa Limonada",
                        private_description: "",
                        public_price: "2000",
                        private_price: "0.0",
                        public_view_order: null,
                        private_view_order: null,
                        public_image_id: -1,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 0,
                    dish_number_of_reviews: 0,
                    reviews: [],
                },
            ],
        },
        {
            category: {
                id: 5,
                public_name: "Postres",
                private_name: "",
                public_description: "Estos son los ricos Postres",
                private_description: "",
                public_view_order: 4,
                private_view_order: null,
                public_image_id: -1,
                private_image_id: -1,
                recently_created: false,
                has_been_modified: false,
                marked_for_deletion: false,
            },
            dishes: [
                {
                    dish: {
                        id: 8,
                        public_name: "Pie de Maracuyá",
                        private_name: "",
                        public_description: "Fabuloso Pie de Maracuyá",
                        private_description: "",
                        public_price: "2500",
                        private_price: "0.0",
                        public_view_order: null,
                        private_view_order: null,
                        public_image_id: -1,
                        private_image_id: -1,
                        previous_dish_number_of_reviews: 0,
                        previous_dish_reviews_average: 0,
                        recently_created: false,
                        marked_for_deletion: false,
                        marked_for_deletion_by_parent: false,
                        has_been_modified: false,
                    },
                    dish_reviews_average: 0,
                    dish_number_of_reviews: 0,
                    reviews: [],
                },
            ],
        },
        {
            category: {
                id: 2,
                public_name: "Licores",
                private_name: "",
                public_description: "Estos son los ricos Licores",
                private_description: "",
                public_view_order: 5,
                private_view_order: null,
                public_image_id: -1,
                private_image_id: -1,
                recently_created: false,
                has_been_modified: false,
                marked_for_deletion: false,
            },
            dishes: [],
        },
    ],
};

// good
